SET UBICACION=E:\BACKUP\mediodia\
SET MOTOR=SERV-VANILLA\SQLEXPRESS2008


SET RUTA=%UBICACION%
MKDIR %RUTA%


sqlcmd -S %MOTOR% -Q "EXEC sp_BackupDatabases @backupLocation='%RUTA%', @backupType='F'" >>%UBICACION%LOG.txt


ECHO BACKUPS DE BASES REALIZADOS CORRECTAMENTE>>%UBICACION%REPORTE.txt 
type %UBICACION%LOG.txt | find /i "BACKUP DATABASE successfully processed" /C >>%UBICACION%REPORTE.txt

ECHO BACKUPS DE BASES REALIZADOS INCORRECTAMENTE>>%UBICACION%REPORTE.txt 
type %UBICACION%LOG.txt | find /i "cannot">>%UBICACION%REPORTE.txt